export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: any;
  /** Represents untyped JSON */
  JSON: any;
};

/** Autogenerated input type of CreateDocument */
export type CreateDocumentInput = {
  body?: InputMaybe<Scalars['JSON']>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
};

/** Autogenerated return type of CreateDocument */
export type CreateDocumentPayload = {
  __typename?: 'CreateDocumentPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  document: Document;
  errors: Array<Scalars['String']>;
};

export type Document = {
  __typename?: 'Document';
  body?: Maybe<Scalars['JSON']>;
  createdAt: Scalars['ISO8601DateTime'];
  id: Scalars['ID'];
  updatedAt: Scalars['ISO8601DateTime'];
};

export type Mutation = {
  __typename?: 'Mutation';
  createDocument?: Maybe<CreateDocumentPayload>;
  updateDocument?: Maybe<UpdateDocumentPayload>;
};


export type MutationCreateDocumentArgs = {
  input: CreateDocumentInput;
};


export type MutationUpdateDocumentArgs = {
  input: UpdateDocumentInput;
};

export type Query = {
  __typename?: 'Query';
  document: Document;
};


export type QueryDocumentArgs = {
  id: Scalars['ID'];
};

/** Autogenerated input type of UpdateDocument */
export type UpdateDocumentInput = {
  body: Scalars['JSON'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated return type of UpdateDocument */
export type UpdateDocumentPayload = {
  __typename?: 'UpdateDocumentPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  document: Document;
  errors: Array<Scalars['String']>;
};
